languages: 
  PHP: true
version: "2"         # required to adjust maintainability checks
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
      ignore_warnings: true
  phpmd:
    enabled: true
    config:
      file_extensions: 
        - php
        - inc
      rulesets: "unusedcode,codesize,naming,cleancode,design"
exclude_paths:
- "tests/*"
checks:
  Naming/ShortVariable:
    enabled: false
  Design/TooManyPublicMethods:
    enabled: false
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
#  similar-code:
#    config:
#      threshold: # language-specific defaults. an override will affect all languages.
#  identical-code:
#    config:
#      threshold: # language-specific defaults. an override will affect all languages
