php:
  - 8.0
  - 8.1

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction
 - wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
 - chmod +x cc-test-reporter
 - ./cc-test-reporter before-build

script:
 - mkdir -p build/logs
 - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls --coverage_clover=build/logs/clover.xml
 - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
